version: "3.8"

services:
  mysqldb:
    platform: Windows/arm64
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_LOCAL_PORT
    healthcheck:
      test: ["docker exec -it some-mysql bash"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
      depends_on:
        - mysqldb
      restart: on-failure
      image: app-docker
      build: .
      env_file: ./.env
      ports:
        - $SPRING_LOCAL_PORT:SPRING_DOCKER_PORT
        - $DEBUG_PORT:$DEBUG_PORT
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQLDB_DATABASE"
          "spring.datasource.username": "$MYSQLDB_USER"
          "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD"
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect"
          "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver"
        }'
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5050"


